# Example config for scripted runs
model_id: runwayml/stable-diffusion-v1-5
prompts:
  - "product mockup, soft studio lighting, neutral bg"
num_images: 2
batch_size: 2
width: 512
height: 512
steps: 30
guidance_scale: 7.5
sampler: DDIM
seed: 1234
